version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend_sehatkita
    ports:
      - "5000:5000"
    # Service MySQL dihapus karena kita pakai RDS AWS
    environment:
      # Data ini akan diambil dari file .env yang kamu buat manual di server
      NODE_ENV: production
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend_sehatkita
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

# Volume mysql_data dihapus biar hemat disk space